# Generated by Django 5.1.2 on 2024-10-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visita_tecnico', '0003_relatoriosvisitas_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatoriosvisitas',
            old_name='observacoes',
            new_name='observacao',
        ),
    ]
