# Generated by Django 5.1.2 on 2024-10-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita_tecnico', '0004_rename_observacoes_relatoriosvisitas_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriosvisitas',
            name='usuario',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
