# Generated by Django 5.1.2 on 2024-10-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitações',
        ),
    ]
